# TEMPLATE

name: serverpod_serialization
version: VERSION
description: Serialization package for Serverpod.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  yaml: ^3.1.1
  uuid: ^4.0.0

dev_dependencies:
  serverpod_lints: VERSION
  test: ^1.24.2

dependency_overrides: #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_lints:  #--CONDITIONALLY_REMOVE_LINE--#
    path: ../serverpod_lints #--CONDITIONALLY_REMOVE_LINE--#