# TEMPLATE

name: serverpod_serialization
version: SERVERPOD_VERSION
description: Serialization package for Serverpod.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: DART_VERSION

dependencies:
  meta: ^1.15.0
  uuid: ^4.5.3
  yaml: ^3.1.2

dev_dependencies:
  serverpod_lints: SERVERPOD_VERSION
  test: ^1.25.5

dependency_overrides:
  serverpod_lints:
    path: ../serverpod_lints
