# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# These are passwords used when running the server locally in development mode
development:
  database: '4DmYGtXIxQYq5tvjUuCCFFrgxqe5AmOt'
  redis: 'DNn7H0_PXGgdMSuZOuLo6hyyzi4YCY6Z'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'P6bXXWpVVtxlN1aaiQOZG0J2cZXXXVcj'

  # Authentication managers configuration
  serverSideSessionKeyHashPepper: 'test_session_key_pepper'
  jwtRefreshTokenHashPepper: 'test_refresh_token_pepper'
  jwtPrivateKey: 'test_private_key'

  # Email Sign In configuration
  emailSecretHashPepper: 'test_email_password_hash_pepper'

  # Google Sign-In configuration
  # The JSON key is in format: {"web":{"client_id": ... } }
  googleClientSecret: 'YOUR_GOOGLE_CLIENT_SECRET_JSON_STRING'

  # Apple Sign In configuration
  appleServiceIdentifier: 'YOUR_APPLE_SERVICE_IDENTIFIER'
  appleBundleIdentifier: 'YOUR_APPLE_BUNDLE_IDENTIFIER'
  appleRedirectUri: 'YOUR_APPLE_REDIRECT_URI'
  appleTeamId: 'YOUR_APPLE_TEAM_ID'
  appleKeyId: 'YOUR_APPLE_KEY_ID'
  appleKey: 'YOUR_APPLE_KEY'

  # Passkey Sign In configuration
  passkeyHostname: 'YOUR_PASSKEY_HOSTNAME'

test:
  database: '0nwsCJtyqm0UlJ9Yjd3fs85S6Gs912'
  redis: 'mtbXuQvKEsG4y3idCgaiYXLbZP3ciU6k'
