name: serverpod_workspace

environment:
  sdk: '>=3.7.0 <4.0.0'
dev_dependencies:
  melos: ^6.1.0

serverpod_cli:
  analyze_pubspecs:
    ignore_packages:
      - google_sign_in
      - sign_in_with_apple
