name: serverpod_auth_core_client
description: Serverpod core authentication client module.
version: 3.0.0-alpha.1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod_client: 3.0.0-alpha.1

dependency_overrides:
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
