# TEMPLATE
PUBLISH_TO

name: serverpod_client
version: VERSION
description: Base classes for communication with the server.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod_serialization: #--CONDITIONAL_COMMENT--#VERSION
    path: ../serverpod_serialization
  http: ">=0.13.0 <2.0.0"
  meta: ^1.8.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  serverpod_lints: #--CONDITIONAL_COMMENT--#VERSION
    path: ../serverpod_lints
  test: ^1.24.2
