# TEMPLATE
PUBLISH_TO

name: serverpod_client
version: VERSION
description: Base classes for communication with the server.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  serverpod_serialization: #^VERSION
    path: ../serverpod_serialization
  http: ^0.13.0
  meta: ^1.8.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
