# TEMPLATE
PUBLISH_TO

name: serverpod_client
version: VERSION
description: Base classes for communication with the server.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  serverpod_serialization: #--CONDITIONAL COMMENT--#VERSION
    path: ../serverpod_serialization
  http: ^0.13.5
  meta: ^1.8.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.0.1
