# TEMPLATE

name: serverpod_auth_server
description: Serverpod authentication server module.
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: DART_VERSION

dependencies:
  crypto: ^3.0.2
  email_validator: '>=2.1.17 <4.0.0'
  googleapis: '>=11.0.0 <17.0.0'
  googleapis_auth: '>=1.6.0 <3.0.0'
  http: '>=1.1.0 <2.0.0'
  image: ^4.0.15
  jose: ^0.3.3
  meta: ^1.15.0
  openid_client: ^0.4.8
  pointycastle: '>=3.7.4 <5.0.0'
  serverpod: SERVERPOD_VERSION
  serverpod_serialization: SERVERPOD_VERSION
  serverpod_shared: SERVERPOD_VERSION

dev_dependencies:
  serverpod_lints: SERVERPOD_VERSION
  serverpod_test: SERVERPOD_VERSION
  test: ^1.25.5

dependency_overrides:
  serverpod:
    path: ../../../../packages/serverpod
  serverpod_lints:
    path: ../../../../packages/serverpod_lints
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
  serverpod_shared:
    path: ../../../../packages/serverpod_shared
  serverpod_test:
    path: ../../../../packages/serverpod_test

false_secrets:
  - test/firebase/firebase_auth_mock.dart
