# TEMPLATE

name: serverpod_auth_backwards_compatibility_server
description: Serverpod authentication backwards compatibility server module.
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: DART_VERSION

dependencies:
  crypto: ^3.0.2
  meta: ^1.11.0
  pointycastle: ^3.7.4
  serverpod: SERVERPOD_VERSION
  serverpod_auth_idp_server: SERVERPOD_VERSION
  serverpod_auth_core_server: SERVERPOD_VERSION
  serverpod_shared: SERVERPOD_VERSION

dev_dependencies:
  serverpod_lints: SERVERPOD_VERSION
  serverpod_test: SERVERPOD_VERSION
  test: ^1.24.2

dependency_overrides:
  serverpod:
    path: ../../../../packages/serverpod
  serverpod_auth_idp_server:
    path: ../../serverpod_auth_idp/serverpod_auth_idp_server
  serverpod_auth_core_server:
    path: ../../serverpod_auth_core/serverpod_auth_core_server
  serverpod_lints:
    path: ../../../../packages/serverpod_lints
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
  serverpod_shared:
    path: ../../../../packages/serverpod_shared
  serverpod_test:
    path: ../../../../packages/serverpod_test
