name: middleware_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod: 3.0.0-rc.1

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  serverpod_test: 3.0.0-rc.1
  test: ^1.25.5

dependency_overrides: 
  serverpod: 
    path: /Users/gianni/src/serverpod/packages/serverpod 
  serverpod_serialization: 
    path: /Users/gianni/src/serverpod/packages/serverpod_serialization 
  serverpod_shared: 
    path: /Users/gianni/src/serverpod/packages/serverpod_shared 
  serverpod_test: 
    path: /Users/gianni/src/serverpod/packages/serverpod_test 
  serverpod_lints: 
    path: /Users/gianni/src/serverpod/packages/serverpod_lints 
