# TEMPLATE

name: auth_example_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod_client: VERSION 
  serverpod_auth_client: VERSION 

dependency_overrides:
  serverpod_client:
    path: ../../../packages/serverpod_client
  serverpod_auth_client:
    path: ../../../modules/serverpod_auth/serverpod_auth_client
  serverpod_serialization:
    path: ../../../packages/serverpod_serialization