# TEMPLATE

name: serverpod_shared
version: SERVERPOD_VERSION
description: Severpod code that is shared between serverpod and tooling.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: DART_VERSION

dependencies:
  yaml: ^3.1.2
  path: ^1.8.2
  super_string: ^1.0.3
  crypto: ^3.0.2
  meta: ^1.11.0

dev_dependencies:
  serverpod_lints: SERVERPOD_VERSION
  test: ^1.24.2
  uuid: ^4.1.0

dependency_overrides:
  serverpod_lints:
    path: ../serverpod_lints
  serverpod_serialization:
    path: ../serverpod_serialization
