# TEMPLATE
PUBLISH_TO

name: serverpod_shared
version: VERSION
description: Severpod code that is shared between serverpod and tooling.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  yaml: ^3.1.0
  super_string: ^1.0.3
  serverpod_client: #^VERSION
    path: ../serverpod_client

dev_dependencies:
  lints: ^2.0.0
