# TEMPLATE

name: serverpod_shared
version: SERVERPOD_VERSION
description: Severpod code that is shared between serverpod and tooling.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  yaml: ^3.1.1
  path: ^1.8.2
  super_string: ^1.0.3
  serverpod_client: SERVERPOD_VERSION
  crypto: ^3.0.2

dev_dependencies:
  serverpod_lints: SERVERPOD_VERSION
  test: ^1.24.2

dependency_overrides:
  serverpod_client:
    path: ../serverpod_client
  serverpod_lints:
    path: ../serverpod_lints
  serverpod_serialization:
    path: ../serverpod_serialization