name: projectname_client
description: Starting point for a Serverpod client.

environment:
  sdk: DART_VERSION

#resolution: workspace #--UNCOMMENT_LINE--#

dependencies:
  serverpod_client: SERVERPOD_VERSION
