name: modulename_server
description: Starting point for a Serverpod module.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod: SERVERPOD_VERSION

dev_dependencies:
  lints: ^3.0.0

dependency_overrides: #--CONDITIONALLY_REMOVE_LINE--#
  serverpod: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_client: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_client #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_serialization: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_serialization #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_service_client: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_service_client #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_shared: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_shared #--CONDITIONALLY_REMOVE_LINE--#