name: auth_example_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  mailer: ^6.0.1
  serverpod:
    path: ../../../packages/serverpod
  serverpod_auth_server:
      path: ../../../modules/serverpod_auth/serverpod_auth_server

dev_dependencies:
  lints: ^2.0.1
