# TEMPLATE

name: serverpod_auth_profile_server
description: Serverpod authentication user profile server module.
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: DART_VERSION

dependencies:
  http: '>=1.0.0 <2.0.0'
  image: ^4.0.15
  meta: ^1.8.0
  serverpod: SERVERPOD_VERSION
  serverpod_auth_user_server: SERVERPOD_VERSION

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
  serverpod_test: SERVERPOD_VERSION
  test: '^1.24.2'

dependency_overrides:
  serverpod:
    path: ../../../../packages/serverpod
  serverpod_auth_user_server:
    path: ../../../new_serverpod_auth/serverpod_auth_user/serverpod_auth_user_server
  serverpod_lints:
    path: ../../../../packages/serverpod_lints
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
  serverpod_shared:
    path: ../../../../packages/serverpod_shared
  serverpod_test:
    path: ../../../../packages/serverpod_test
