name: chat_server
description: Starting point for a Serverpod server.

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  serverpod:
    path: ../../../packages/serverpod
  serverpod_auth_server:
    path: ../../../modules/serverpod_auth/serverpod_auth_server
  serverpod_chat_server:
    path: ../../../modules/serverpod_chat/serverpod_chat_server

dev_dependencies:
  lints: ^2.0.1
