name: projectname
publish_to: none

environment:
  sdk: DART_VERSION

#workspace: #--UNCOMMENT_LINE--#
#  - projectname_client #--UNCOMMENT_LINE--#
#  - projectname_server #--UNCOMMENT_LINE--#
#  - projectname_flutter #--UNCOMMENT_LINE--#

dependency_overrides: #--CONDITIONALLY_REMOVE_LINE--#
  serverpod: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_serialization: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_serialization #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_shared: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_shared #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_test: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_test #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_lints: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_lints #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_client: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_client #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_flutter: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../../../packages/serverpod_flutter #--CONDITIONALLY_REMOVE_LINE--#
