# This is the configuration file for your local development environment. By
# default, it runs a single server on port 8080. To set up your server, you will
# need to add the name of the database you are connecting to and the user name.
# The password for the database is stored in the config/passwords.yaml.

cluster:
  0:
    # Main port to run the server on.
    port: 8080
    # Service port, used for communication between servers in a cluster or for
    # gaining insights from the server while it's running.
    servicePort: 8081
    # Host used to connect to the server.
    address: localhost

# This is the database setup for your server. You will need to edit this to get
# the server up and running.
database:
  host: localhost
  port: 5432
  name: serverpod_example
  user: my_database_user # <-- UPDATE with your database user name
