# TEMPLATE

name: auth_example_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: DART_VERSION

dependencies:
  mailer: ^6.0.1
  serverpod: SERVERPOD_VERSION
  serverpod_auth_server: SERVERPOD_VERSION

dev_dependencies:
  lints: ^3.0.0

dependency_overrides:
  serverpod:
    path: ../../../packages/serverpod
  serverpod_auth_server:
      path: ../../../modules/serverpod_auth/serverpod_auth_server
  serverpod_client:
    path: ../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../packages/serverpod_serialization
  serverpod_service_client:
    path: ../../../packages/serverpod_service_client
  serverpod_shared:
    path: ../../../packages/serverpod_shared