# This is the configuration file for your local development environment. By
# default, it runs a single server on port 8080. To set up your server, you will
# need to add the name of the database you are connecting to and the user name.
# The password for the database is stored in the config/passwords.yaml.

# Defines public facing access to the server, in development mode this is
# typically the same as your server setup.
publicHost: localhost
publicPort: 8080
publicScheme: http

# Main port to run the server on.
port: 8080
# Service port, used for insights from the server while it's running.
servicePort: 8081

# This is the database setup for your server.
database:
  host: localhost
  port: 8090
  name: projectname
  user: postgres

# This is the setup for Redis.
redis:
  host: localhost
  port: 8091