# TEMPLATE
PUBLISH_TO

name: serverpod_chat_flutter
description: Flutter widgets for the Serverpod chat module.
version: VERSION
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^4.2.1
  intl: ^0.17.0
  url_launcher: ^6.0.17
  path: ^1.8.2
  serverpod_auth_client: #^VERSION
    path: ../../serverpod_auth/serverpod_auth_client
  serverpod_chat_client: #^VERSION
    path: ../serverpod_chat_client
  serverpod_auth_shared_flutter: #^VERSION
    path: ../../serverpod_auth/serverpod_auth_shared_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.2.0

flutter:
