# TEMPLATE

name: serverpod_auth_bridge_client
description: Serverpod authentication backwards compatibility client module.
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: DART_VERSION

dependencies:
  serverpod_auth_core_client: SERVERPOD_VERSION
  serverpod_auth_idp_client: SERVERPOD_VERSION
  serverpod_client: SERVERPOD_VERSION

dependency_overrides:
  serverpod_auth_core_client:
    path: ../../serverpod_auth_core/serverpod_auth_core_client
  serverpod_auth_idp_client:
    path: ../../serverpod_auth_idp/serverpod_auth_idp_client
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
