name: example_client
description: Starting point for a Serverpod client.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_auth_client:
    path: ../../../../modules/serverpod_auth/serverpod_auth_client
  serverpod_chat_client:
    path: ../../../../modules/serverpod_chat/serverpod_chat_client

dev_dependencies:
  lints: ^2.0.0