# TEMPLATE
PUBLISH_TO

name: serverpod_cli
version: VERSION
description: Command line tools for Serverpod.
repository: https://github.com/serverpod/serverpod

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  archive: ^3.3.7
  args: ^2.4.0
  ci: ^0.1.0
  code_builder: ^4.4.0
  colorize: ^3.0.0
  dart_style: ^2.3.0
  http: ^0.13.5
  intl: ^0.17.0
  recase: ^4.1.0
  built_collection: ^5.1.1
  package_config: ^2.1.0
  pubspec_parse: ^1.2.2
  source_span: ^1.10.0
  super_string: ^1.0.3
  watcher: ^1.0.2
  analyzer: ^5.10.0
  path: ^1.8.2
  pub_api_client: ^2.4.0
  uuid: ^3.0.7
  yaml: ^3.1.1
  serverpod_shared: #^VERSION
    path: ../../packages/serverpod_shared
  serverpod_service_client: #^VERSION
    path: ../../packages/serverpod_service_client
  async: ^2.11.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2

executables:
  serverpod: serverpod_cli
