# TEMPLATE
PUBLISH_TO

name: serverpod_cli
version: VERSION
description: Command line tools for Serverpod.
repository: https://github.com/serverpod/serverpod

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.1.2
  args: ^2.0.0
  colorize: ^3.0.0
  http: ^0.13.3
  intl: ^0.17.0
  recase: ^4.0.0
  watcher: ^1.0.0
  analyzer: ^1.3.0
  path: ^1.8.0
  yaml: ^3.1.0
  serverpod_shared: #^VERSION
    path: ../../packages/serverpod_shared

executables:
  serverpod: serverpod_cli
