# TEMPLATE

name: serverpod_cli
version: VERSION
description: Command line tools for Serverpod.
repository: https://github.com/serverpod/serverpod

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.3.7
  args: ^2.4.0
  ci: ^0.1.0
  code_builder: ^4.4.0
  dart_style: ^2.3.0
  http: ">=0.13.0 <2.0.0"
  intl: ^0.18.0
  recase: ^4.1.0
  built_collection: ^5.1.1
  package_config: ^2.1.0
  pubspec_parse: ^1.2.2
  source_span: ^1.10.0
  super_string: ^1.0.3
  watcher: ^1.0.2
  analyzer: ^6.0.0
  path: ^1.8.2
  pub_api_client: ^2.4.0
  uuid: ^4.0.0
  yaml: ^3.1.1
  serverpod_shared: VERSION
  serverpod_serialization: VERSION
  serverpod_service_client: VERSION
  async: ^2.11.0
  meta: ^1.8.0
  json_rpc_2: ^3.0.2
  stream_channel: ^2.1.1
  lsp_server: ^0.3.0
  pub_semver: ^2.1.4


dev_dependencies:
  serverpod_lints: VERSION
  test: ^1.24.2

dependency_overrides:
  serverpod_shared:
    path: ../../packages/serverpod_shared
  serverpod_serialization:
    path: ../../packages/serverpod_serialization
  serverpod_service_client:
    path: ../../packages/serverpod_service_client
  serverpod_lints:
    path: ../../packages/serverpod_lints
  serverpod_client:
    path: ../../packages/serverpod_client

executables:
  serverpod: serverpod_cli
