name: serverpod_auth_core_client
description: Serverpod core authentication client module.
version: SERVERPOD_VERSION

environment:
  sdk: DART_VERSION

dependencies:
  clock: ^1.1.1
  serverpod_client: SERVERPOD_VERSION

dev_dependencies:
  test: ^1.25.5

dependency_overrides:
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
