name: modulename
publish_to: none

environment:
  sdk: '^3.8.0'

#workspace: #--UNCOMMENT_LINE--#
#  - modulename_client #--UNCOMMENT_LINE--#
#  - modulename_server #--UNCOMMENT_LINE--#

dependency_overrides: 
  serverpod: 
    path: ../../../packages/serverpod 
  serverpod_serialization: 
    path: ../../../packages/serverpod_serialization 
  serverpod_shared: 
    path: ../../../packages/serverpod_shared 
  serverpod_test: 
    path: ../../../packages/serverpod_test 
  serverpod_lints: 
    path: ../../../packages/serverpod_lints 
  serverpod_client: 
    path: ../../../packages/serverpod_client 
