name: modulename
publish_to: none

environment:
  sdk: '^3.8.0'

#workspace:
#  - modulename_client
#  - modulename_server

dependency_overrides: 
  serverpod: 
    path: ../../../packages/serverpod 
  serverpod_serialization: 
    path: ../../../packages/serverpod_serialization 
  serverpod_shared: 
    path: ../../../packages/serverpod_shared 
  serverpod_test: 
    path: ../../../packages/serverpod_test 
  serverpod_lints: 
    path: ../../../packages/serverpod_lints 
  serverpod_client: 
    path: ../../../packages/serverpod_client 
