name: projectname_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod_client: 1.2.1

dependency_overrides: 
  serverpod_client: 
    path: ../../../packages/serverpod_client 
  serverpod_serialization: 
    path: ../../../packages/serverpod_serialization 