name: projectname_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  serverpod_client: #--CONDITIONAL COMMENT--#VERSION
    path: ../../../packages/serverpod_client
