# TEMPLATE

name: serverpod_cloud_storage_s3_compat
description: Base package for S3-compatible cloud storage integrations with Serverpod
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: DART_VERSION

dependencies:
  amazon_cognito_identity_dart_2: ^3.5.0
  crypto: ^3.0.2
  http: '>=1.1.0 <2.0.0'
  path: ^1.8.3
  serverpod: SERVERPOD_VERSION

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: ^1.25.5

dependency_overrides:
  serverpod:
    path: ../../packages/serverpod
  serverpod_serialization:
    path: ../../packages/serverpod_serialization
  serverpod_shared:
    path: ../../packages/serverpod_shared
