name: modulename_client
description: Starting point for a Serverpod module client.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '^3.8.0'

#resolution: workspace

dependencies:
  serverpod_client: 3.0.1
