name: modulename_client
description: Starting point for a Serverpod module client.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  serverpod_client: #--CONDITIONAL COMMENT--#VERSION
    path: ../../../packages/serverpod_client
