# TEMPLATE

name: serverpod_lints
description: Lints used by internal Serverpod packages.
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_lints: ^3.0.0
  lints: ^3.0.0
