# TEMPLATE
PUBLISH_TO

name: serverpod_chat_server
description: Serverpod chat server module.
version: VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  serverpod: #^VERSION
    path: ../../../packages/serverpod
  serverpod_auth_server: #^VERSION
    path: ../../serverpod_auth/serverpod_auth_server
  http: ^0.13.5
  image: ^3.0.2
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
