# TEMPLATE
PUBLISH_TO

name: serverpod_chat_server
description: Serverpod chat server module.
version: VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  serverpod: #^VERSION
    path: ../../../packages/serverpod
  serverpod_auth_server: #^VERSION
    path: ../../serverpod_auth/serverpod_auth_server
  serverpod_serialization: #^VERSION
    path: ../../../packages/serverpod_serialization/
  http: ^0.13.5
  image: ^4.0.15
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.1
