# TEMPLATE

name: serverpod_chat_server
description: Serverpod chat server module.
version: VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod: VERSION
  serverpod_auth_server: VERSION
  serverpod_serialization: VERSION
  http: ">=0.13.0 <2.0.0"
  dio: ^5.4.0
  image: ^4.0.15
  path: ^1.8.2

dev_dependencies:
  serverpod_lints: VERSION

dependency_overrides:
  serverpod:
    path: ../../../packages/serverpod
  serverpod_auth_server:
    path: ../../serverpod_auth/serverpod_auth_server
  serverpod_serialization:
    path: ../../../packages/serverpod_serialization/
  serverpod_lints:
    path: ../../../packages/serverpod_lints
  serverpod_client:
    path: ../../../packages/serverpod_client
  serverpod_service_client:
    path: ../../../packages/serverpod_service_client
  serverpod_shared:
    path: ../../../packages/serverpod_shared