# TEMPLATE

name: serverpod_auth_server
description: Serverpod authentication server module.
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod

environment:
  sdk: DART_VERSION

dependencies:
  serverpod: SERVERPOD_VERSION
  serverpod_serialization: SERVERPOD_VERSION
  serverpod_shared: SERVERPOD_VERSION
  crypto: ^3.0.2
  email_validator: '>=2.1.17 <4.0.0'
  openid_client: ^0.4.8
  meta: ^1.11.0
  googleapis: '>=11.0.0 <15.0.0'
  googleapis_auth: '>=1.6.0 <3.0.0'
  http: '>=1.0.0 <2.0.0'
  image: ^4.0.15
  jose: ^0.3.3
  pointycastle: ^3.7.4

dev_dependencies:
  serverpod_lints: SERVERPOD_VERSION
  test: ^1.24.2
  serverpod_test: SERVERPOD_VERSION

dependency_overrides:
  serverpod:
    path: ../../../packages/serverpod
  serverpod_serialization:
    path: ../../../packages/serverpod_serialization
  serverpod_lints:
    path: ../../../packages/serverpod_lints
  serverpod_shared:
    path: ../../../packages/serverpod_shared
  serverpod_test:
    path: ../../../packages/serverpod_test

false_secrets:
  - test/firebase/firebase_auth_mock.dart
