name: middleware_client
description: Starting point for a Serverpod client.

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod_client: 3.0.0-rc.1

dependency_overrides: 
  serverpod_client: 
    path: /Users/gianni/src/serverpod/packages/serverpod_client 
  serverpod_serialization: 
    path: /Users/gianni/src/serverpod/packages/serverpod_serialization 
