name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.0.1'
      SERVERPOD_PASSWORD_database: 'JGTYGM5c3pJou-A1GHA0Hj5zm8NLnSYm'
      SERVERPOD_PASSWORD_redis: 'aTvMkH2Ey8fC-Zab3zkYjYAWg82v_eOe'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: flutter_web_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: flutter_web_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: flutter_web_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: flutter_web_server
        run: serverpod generate

      - name: Run tests
        working-directory: flutter_web_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: flutter_web_server
        run: docker compose down -v
