# TEMPLATE

name: serverpod_flutter
description: Flutter specific utilities for Serverpod.
version: VERSION
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  connectivity_plus: ^5.0.0
  serverpod_client: VERSION
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  serverpod_lints: VERSION

dependency_overrides: #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_client: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../serverpod_client #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_lints: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../serverpod_lints #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_serialization: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../serverpod_serialization #--CONDITIONALLY_REMOVE_LINE--#
#--CONDITIONALLY_REMOVE_LINE--#
flutter:
