# TEMPLATE

name: serverpod_flutter
description: Flutter specific utilities for Serverpod.
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  connectivity_plus: ^5.0.0
  serverpod_client: SERVERPOD_VERSION
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  serverpod_lints: SERVERPOD_VERSION

dependency_overrides:
  serverpod_client:
    path: ../serverpod_client
  serverpod_lints:
    path: ../serverpod_lints
  serverpod_serialization:
    path: ../serverpod_serialization

flutter:
