# TEMPLATE

name: serverpod
version: VERSION
description: Serverpod is an open-source, scalable app server, written in Dart for the Flutter community.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues
documentation: https://docs.serverpod.dev

topics:
  - backend
  - server
  - network
  - rest
  - database

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.0
  collection: ^1.17.1
  crypto: ^3.0.2
  http: ">=0.13.0 <2.0.0"
  meta: ^1.8.0
  mustache_template: ^2.0.0
  path: ^1.8.2
  postgres: ^2.6.1
  redis: ^4.0.0
  retry: ^3.1.1
  synchronized: ^3.1.0
  postgres_pool: ^2.1.6
  system_resources: ^1.6.0
  vm_service: ">=13.0.0 <15.0.0"
  yaml: ^3.1.1
  serverpod_shared: VERSION
  serverpod_serialization: VERSION
  serverpod_service_client: VERSION
  serverpod_client: VERSION

dev_dependencies:
  test: ^1.24.2
  serverpod_lints: VERSION

dependency_overrides: #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_shared: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../serverpod_shared #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_serialization: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../serverpod_serialization #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_service_client: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../serverpod_service_client #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_client: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../serverpod_client #--CONDITIONALLY_REMOVE_LINE--#
  serverpod_lints: #--CONDITIONALLY_REMOVE_LINE--#
    path: ../serverpod_lints #--CONDITIONALLY_REMOVE_LINE--#