# TEMPLATE

name: serverpod
version: SERVERPOD_VERSION
description: Serverpod is an open-source, scalable app server, written in Dart for the Flutter community.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues
documentation: https://docs.serverpod.dev

topics:
  - backend
  - server
  - network
  - rest
  - database

environment:
  sdk: DART_VERSION

dependencies:
  args: ^2.7.0
  collection: ^1.18.0
  crypto: ^3.0.2
  http: '>=1.1.0 <2.0.0'
  meta: ^1.15.0
  mustache_template: ^2.0.0
  path: ^1.8.3
  postgres: ^3.4.0
  redis: ^4.0.0
  relic: ^0.15.1
  retry: ^3.1.1
  serverpod_serialization: SERVERPOD_VERSION
  serverpod_shared: SERVERPOD_VERSION
  synchronized: ^3.1.0
  system_resources: ^1.6.0
  uuid: ^4.1.0
  vm_service: '>=13.0.0 <16.0.0'
  web_socket: ^1.0.1
  yaml: ^3.1.2

dev_dependencies:
  serverpod_lints: SERVERPOD_VERSION
  test: ^1.25.5
  test_descriptor: ^2.0.2

dependency_overrides:
  serverpod_lints:
    path: ../serverpod_lints
  serverpod_serialization:
    path: ../serverpod_serialization
  serverpod_shared:
    path: ../serverpod_shared
