# TEMPLATE
PUBLISH_TO

name: serverpod
version: VERSION
description: Serverpod is an open-source, scalable app server, written in Dart for the Flutter community.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues
documentation: https://docs.serverpod.dev

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.4.0
  collection: ^1.15.0
  crypto: ^3.0.2
  http: ^0.13.5
  meta: ^1.8.0
  mustache_template: ^2.0.0
  path: ^1.8.2
  postgres: ^2.6.0
  redis: ^3.1.0
  retry: ^3.1.0
  synchronized: ^3.0.0+2
  postgres_pool: ^2.1.6
  system_resources: ^1.6.0
  vm_service: ^9.4.0
  yaml: ^3.1.1
  serverpod_shared: #^VERSION
    path: ../serverpod_shared
  serverpod_serialization: #^VERSION
    path: ../serverpod_serialization
  serverpod_service_client: #^VERSION
    path: ../serverpod_service_client
  serverpod_client: #^VERSION
    path: ../serverpod_client

dev_dependencies:
  test: ^1.21.4
  lints: ^2.0.0
