# TEMPLATE

name: serverpod_auth_core_flutter
description: Serverpod core authentication Flutter module.
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: DART_VERSION
  flutter: FLUTTER_VERSION

dependencies:
  clock: ^1.1.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  meta: ^1.15.0
  serverpod_auth_core_client: SERVERPOD_VERSION

dev_dependencies:
  flutter_test:
    sdk: flutter
  serverpod_lints: SERVERPOD_VERSION

dependency_overrides:
  serverpod_auth_core_client:
    path: ../serverpod_auth_core_client
  serverpod_client:
    path: ../../../../packages/serverpod_client
  serverpod_lints:
    path: ../../../../packages/serverpod_lints
  serverpod_serialization:
    path: ../../../../packages/serverpod_serialization
