name: auth_example_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod_client:
    path: ../../../packages/serverpod_client
  serverpod_auth_client:
    path: ../../../modules/serverpod_auth/serverpod_auth_client
