# TEMPLATE
PUBLISH_TO

name: serverpod_chat_client
description: Serverpod chat module client.
version: VERSION
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  serverpod_client: #--CONDITIONAL_COMMENT--#VERSION
    path: ../../../packages/serverpod_client
  serverpod_auth_client: #--CONDITIONAL_COMMENT--#VERSION
    path: ../../serverpod_auth/serverpod_auth_client
