# TEMPLATE

name: serverpod_test
version: SERVERPOD_VERSION
description: Severpod test tools to simplify testing of endpoints.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: DART_VERSION

dependencies:
  meta: ^1.15.0
  serverpod: SERVERPOD_VERSION
  serverpod_lints: SERVERPOD_VERSION
  synchronized: ^3.1.0
  test: ^1.25.5

dependency_overrides:
  serverpod:
    path: ../serverpod
  serverpod_lints:
    path: ../serverpod_lints
  serverpod_serialization:
    path: ../serverpod_serialization
  serverpod_shared:
    path: ../serverpod_shared
