# TEMPLATE
PUBLISH_TO

name: serverpod_auth_client
description: Serverpod authentication client.
version: VERSION
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  lints: ^2.0.0
  serverpod_client: #^VERSION
    path: ../../../packages/serverpod_client
