name: modulename_server
description: Starting point for a Serverpod module.

environment:
  sdk: '^3.8.0'

#resolution: workspace #--UNCOMMENT_LINE--#

dependencies:
  serverpod: 3.2.1

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  serverpod_test: 3.2.1
  test: ^1.25.5
