name: modulename_server
description: Starting point for a Serverpod module.

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  serverpod: 2.0.0-alpha.3

dev_dependencies:
  lints: ^3.0.0

dependency_overrides: 
  serverpod: 
    path: ../../../packages/serverpod 
  serverpod_serialization: 
    path: ../../../packages/serverpod_serialization 
  serverpod_shared: 
    path: ../../../packages/serverpod_shared 