name: modulename_server
description: Starting point for a Serverpod module.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod: 1.2.2-rc.1

dev_dependencies:
  lints: ^3.0.0

dependency_overrides: 
  serverpod: 
    path: ../../../packages/serverpod 
  serverpod_client: 
    path: ../../../packages/serverpod_client 
  serverpod_serialization: 
    path: ../../../packages/serverpod_serialization 
  serverpod_service_client: 
    path: ../../../packages/serverpod_service_client 
  serverpod_shared: 
    path: ../../../packages/serverpod_shared 