name: modulename_server
description: Starting point for a Serverpod module.

environment:
  sdk: '^3.8.0'

#resolution: workspace

dependencies:
  serverpod: 3.0.1

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  serverpod_test: 3.0.1
  test: ^1.25.5
