name: modulename_server
description: Starting point for a Serverpod module.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  serverpod: #^VERSION
    path: ../../../packages/serverpod

dev_dependencies:
  lints: ^2.0.1
