name: modulename_server
description: Starting point for a Serverpod module.

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod: 3.1.0

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  serverpod_test: 3.1.0
  test: ^1.25.5

dependency_overrides: 
  serverpod: 
    path: ../../../packages/serverpod 
  serverpod_serialization: 
    path: ../../../packages/serverpod_serialization 
  serverpod_shared: 
    path: ../../../packages/serverpod_shared 
  serverpod_test: 
    path: ../../../packages/serverpod_test 
  serverpod_lints: 
    path: ../../../packages/serverpod_lints 
