# TEMPLATE
PUBLISH_TO

name: serverpod_cloud_storage_s3
description: Serverpod integration for S3 cloud storage
version: VERSION
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: '>=2.19.0 <4.0.0'


dependencies:
  serverpod: #--CONDITIONAL COMMENT--#VERSION
    path: ../../packages/serverpod
  amazon_cognito_identity_dart_2: ^1.0.3
  http: ^0.13.5
  built_collection: ^5.1.1
  built_value: ^8.4.4
  path: ^1.8.2
  xml2json: ^5.3.6

dev_dependencies:
  lints: ^2.0.1
