# TEMPLATE

name: serverpod_cloud_storage_s3
description: Serverpod integration for S3 cloud storage
version: SERVERPOD_VERSION
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: DART_VERSION

dependencies:
  serverpod: SERVERPOD_VERSION
  serverpod_cloud_storage_s3_compat: SERVERPOD_VERSION

dev_dependencies:
  lints: ">=3.0.0 <7.0.0"
  test: ^1.25.5

dependency_overrides:
  serverpod:
    path: ../../packages/serverpod
  serverpod_client:
    path: ../../packages/serverpod_client
  serverpod_cloud_storage_s3_compat:
    path: ../serverpod_cloud_storage_s3_compat
  serverpod_serialization:
    path: ../../packages/serverpod_serialization
  serverpod_shared:
    path: ../../packages/serverpod_shared
