# TEMPLATE
PUBLISH_TO

name: serverpod_service_client
version: VERSION
description: Generated client for the Severpod service protocol.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  serverpod_client: #^VERSION
    path: ../serverpod_client
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
